apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: download-rte-ccr
  namespace: noos-cron
spec:
  schedule: "10 12 * * *"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: script
              image: 254367186279.dkr.ecr.eu-west-1.amazonaws.com/noos-prod/airflow-etl/worker
              imagePullPolicy: Always
              args: ["python", "download_rte_ccr.py"]
              envFrom:
                - secretRef:
                    name: manualcron-dotenv
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: download-rte-epex
  namespace: noos-cron
spec:
  schedule: "10 15 * * *"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: script
              image: 254367186279.dkr.ecr.eu-west-1.amazonaws.com/noos-prod/airflow-etl/worker
              imagePullPolicy: Always
              args: ["python", "download_rte_epex.py"]
              envFrom:
                - secretRef:
                    name: manualcron-dotenv
---
