apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: manualcron
  namespace: noos-cron
spec:
  schedule: "0 12 * * *"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: script
              image: 254367186279.dkr.ecr.eu-west-1.amazonaws.com/noos-prod/airflow-etl/worker
              imagePullPolicy: Always
              args: ["python", "rte_api.py"]
              envFrom:
                - secretRef:
                    name: manualcron-dotenv

