version: 1
disable_existing_loggers: false



formatters:
    standard:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: standard
        stream: ext://sys.stdout

root:
    level: NOTSET
    handlers: [console]
    propagate: yes

loggers:
    <module>:
        level: INFO
        handlers: [console]
        propagate: yes
