---
version: 2.1

parameters:
  montly_trigger:
    type: boolean
    default: false

filters:
  filter: &filter_master_only
    branches:
      only: master
  hold: &hold_master_only
    type: approval
    filters:
      <<: *filter_master_only
  build: &build_master_only
    context: DOCKERHUB_SHARED
    filters:
      <<: *filter_master_only
  manual_build: &manual_build_master_only
    requires:
      - hold
    <<: *build_master_only

# ----------------
# Orbs declaration
# ----------------

orbs:
  noos-ci: noosenergy/noos-ci@0.1.17

# -------------
# Pipeline jobs
# -------------

jobs:
  build_image_circleci:
    executor: noos-ci/default
    steps:
      - checkout
      - noos-ci/docker_build_image:
          registry_provider: docker
          image_context: ./docker/circleci
          image_name: circleci
          image_tag: ${CIRCLE_SHA1}

  build_image_dbbackup:
    executor: noos-ci/default
    steps:
      - checkout
      - noos-ci/docker_build_image:
          registry_provider: docker
          image_context: ./docker/dbbackup
          image_name: dbbackup
          image_tag: ${CIRCLE_SHA1}

  build_image_jupyterlab:
    executor: noos-ci/default
    steps:
      - checkout
      - noos-ci/docker_build_image:
          registry_provider: docker
          image_context: ./docker/jupyterlab
          image_name: jupyterlab
          image_tag: ${CIRCLE_SHA1}

  build_image_pyscript:
    executor: noos-ci/default
    steps:
      - checkout
      - noos-ci/docker_build_image:
          registry_provider: docker
          image_context: ./docker/pyscript
          image_name: pyscript
          image_tag: ${CIRCLE_SHA1}

# ------------------
# Pipeline workflows
# ------------------

workflows:
  monthly_build_images:
    when: << pipeline.parameters.montly_trigger >>
    jobs:
      - build_image_circleci:
          <<: *build_master_only
      - build_image_dbbackup:
          <<: *build_master_only
      - build_image_jupyterlab:
          <<: *build_master_only
      - build_image_pyscript:
          <<: *build_master_only

  build_image_circleci:
    jobs:
      - hold:
          <<: *hold_master_only
      - build_image_circleci:
          <<: *manual_build_master_only

  build_image_dbbackup:
    jobs:
      - hold:
          <<: *hold_master_only
      - build_image_dbbackup:
          <<: *manual_build_master_only

  build_image_jupyterlab:
    jobs:
      - hold:
          <<: *hold_master_only
      - build_image_jupyterlab:
          <<: *manual_build_master_only

  build_image_pyscript:
    jobs:
      - hold:
          <<: *hold_master_only
      - build_image_pyscript:
          <<: *manual_build_master_only
