---
version: 2.1

# ----------------
# Orbs declaration
# ----------------

orbs:

  noos-ci: noosenergy/noos-ci@0.1.9


# --------------
# Pipeline tasks
# --------------

jobs:

  build-dbbackup:
    executor: noos-ci/default
    steps:
      - checkout
      - noos-ci/docker-build-image:
          registry-provider: docker
          image-context: ./docker/db-backup
          image-name: db-backup
          image-tag: ${CIRCLE_SHA1}

  build-jupyterhub:
    executor: noos-ci/default
    steps:
      - checkout
      - noos-ci/docker-build-image:
          registry-provider: docker
          image-context: ./docker/jupyterhub
          image-name: jupyterhub
          image-tag: ${CIRCLE_SHA1}

  build-jupyterlab:
    executor: noos-ci/default
    steps:
      - checkout
      - noos-ci/docker-build-image:
          registry-provider: docker
          image-context: ./docker/jupyterlab
          image-name: jupyterlab
          image-tag: ${CIRCLE_SHA1}


# -----------------
# Pipeline workflow
# -----------------

workflows:

  build-dbbackup:
    jobs:
      - hold:
          type: approval
          filters: &filter-master-only
            branches:
              only: master
      - build-dbbackup:
          context: CIRCLECI_SHARED
          filters:
            <<: *filter-master-only

  build-jupyterhub:
    jobs:
      - hold:
          type: approval
          filters:
            <<: *filter-master-only
      - build-jupyterhub:
          context: CIRCLECI_SHARED
          requires:
            - hold
          filters:
            <<: *filter-master-only

  build-jupyterlab:
    jobs:
      - hold:
          type: approval
          filters:
            <<: *filter-master-only
      - build-jupyterlab:
          context: CIRCLECI_SHARED
          requires:
            - hold
          filters:
            <<: *filter-master-only
