---
version: 2.1

# ------------------
# Reusable executors
# ------------------

executors:

  standard:
    docker:
      - image: circleci/buildpack-deps:stretch
    working_directory: "~/app"

# -----------------
# Reusable commands
# -----------------

commands:

  build_push_image:
    steps:
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build and tag Docker images
          command: |
            make docker-build
            make docker-tag
      - run:
          name: Push Docker images to Docker Hub
          command: |
            make docker-login
            make docker-push

# --------------
# Pipeline tasks
# --------------

jobs:

  build-dbbackup:
    executor: standard
    environment:
      IMAGE_TAG: ${CIRCLE_SHA1}
      COMPONENT: "db-backup"
    steps:
      - checkout
      - build_push_image

  build-jupyterhub:
    executor: standard
    environment:
      IMAGE_TAG: ${CIRCLE_SHA1}
      COMPONENT: "jupyterhub"
    steps:
      - checkout
      - build_push_image

  build-jupyterlab:
    executor: standard
    environment:
      IMAGE_TAG: ${CIRCLE_SHA1}
      COMPONENT: "jupyterlab"
    steps:
      - checkout
      - build_push_image

# -----------------
# Pipeline workflow
# -----------------

workflows:

  build:
    jobs:
      - build-dbbackup:
          context: CIRCLECI_SHARED
          filters:
            branches:
              only: master
      - build-jupyterhub:
          context: CIRCLECI_SHARED
          filters:
            branches:
              only: fix/correct-path-assets
      - build-jupyterlab:
          context: CIRCLECI_SHARED
          filters:
            branches:
              only: master
