# https://circleci.com/docs/2.1/language-python/
version: 2.1

# ------------------
# Reusable executors
# ------------------

executors:

  standard:
    docker:
      - image: circleci/buildpack-deps:stretch
    working_directory: "~/app"

# -----------------
# Reusable commands
# -----------------

commands:

  build_push_image:
    steps:
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build and tag Docker images
          command: |
            make docker-build
            make docker-tag
      - run:
          name: Push Docker images to Docker Hub
          command: |
            make docker-login
            make docker-push

# --------------
# Pipeline tasks
# --------------

jobs:

  build-dbbackup:
    executor: standard
    environment:
      IMAGE_TAG: ${CIRCLE_SHA1}
      COMPONENT: "db-backup"
    steps:
      - checkout
      - build_push_image

  build-jupyter:
    executor: standard
    environment:
      IMAGE_TAG: ${CIRCLE_SHA1}
      COMPONENT: "jupyter"
    steps:
      - checkout
      - build_push_image

# -----------------
# Pipeline workflow
# -----------------

#workflows:

  version: 2

  build:
    jobs:
      - build-dbbackup:
          filters:
            branches:
              only: master
      - build-jupyter:
          filters:
            branches:
              only: master
