---
version: 2.1

# ----------------
# Orbs declaration
# ----------------

orbs:

  noos-ci: noosenergy/noos-ci@0.1.11


# --------------
# Pipeline tasks
# --------------

jobs:

  build-image-base:
    executor: noos-ci/default
    steps:
      - checkout
      - noos-ci/docker-build-image:
          registry-provider: docker
          image-context: ./docker/base
          image-name: base
          image-tag: ${CIRCLE_SHA1}

  build-image-circleci:
    executor: noos-ci/default
    steps:
      - checkout
      - noos-ci/docker-build-image:
          registry-provider: docker
          image-context: ./docker/circleci
          image-name: circleci
          image-tag: ${CIRCLE_SHA1}

  build-image-dbbackup:
    executor: noos-ci/default
    steps:
      - checkout
      - noos-ci/docker-build-image:
          registry-provider: docker
          image-context: ./docker/dbbackup
          image-name: dbbackup
          image-tag: ${CIRCLE_SHA1}

  build-image-jupyterhub:
    executor: noos-ci/default
    steps:
      - checkout
      - noos-ci/docker-build-image:
          registry-provider: docker
          image-context: ./docker/jupyterhub
          image-name: jupyterhub
          image-tag: ${CIRCLE_SHA1}

  build-image-jupyterlab:
    executor: noos-ci/default
    steps:
      - checkout
      - noos-ci/docker-build-image:
          registry-provider: docker
          image-context: ./docker/jupyterlab
          image-name: jupyterlab
          image-tag: ${CIRCLE_SHA1}


# -----------------
# Pipeline workflow
# -----------------

workflows:

  build-image-base:
    jobs:
      - hold:
          type: approval
          filters: &filter-master-only
            branches:
              only: master
      - build-image-base:
          context: CIRCLECI_SHARED
          requires:
            - hold
          filters:
            <<: *filter-master-only

  build-image-circleci:
    jobs:
      - hold:
          type: approval
          filters: &filter-master-only
            branches:
              only: master
      - build-image-circleci:
          context: CIRCLECI_SHARED
          requires:
            - hold
          filters:
            <<: *filter-master-only

  build-image-dbbackup:
    jobs:
      - hold:
          type: approval
          filters: &filter-master-only
            branches:
              only: master
      - build-image-dbbackup:
          context: CIRCLECI_SHARED
          requires:
            - hold
          filters:
            <<: *filter-master-only

  build-image-jupyterhub:
    jobs:
      - hold:
          type: approval
          filters:
            <<: *filter-master-only
      - build-image-jupyterhub:
          context: CIRCLECI_SHARED
          requires:
            - hold
          filters:
            <<: *filter-master-only

  build-image-jupyterlab:
    jobs:
      - hold:
          type: approval
          filters:
            <<: *filter-master-only
      - build-image-jupyterlab:
          context: CIRCLECI_SHARED
          requires:
            - hold
          filters:
            <<: *filter-master-only
