---
version: 2.1

default:
  filter: &filter-master-only
    branches:
      only: master
  hold: &hold-master-only
    type: approval
    filters:
      <<: *filter-master-only
  build: &deploy-master-only
    context: DOCKERHUB_SHARED
    requires:
      - hold
    filters:
      <<: *filter-master-only


# ----------------
# Orbs declaration
# ----------------

orbs:

  noos-ci: noosenergy/noos-ci@0.1.15


# --------------
# Pipeline tasks
# --------------

jobs:

  build-image-circleci:
    executor: noos-ci/default
    steps:
      - checkout
      - noos-ci/docker-build-image:
          registry-provider: docker
          image-context: ./docker/circleci
          image-name: circleci
          image-tag: ${CIRCLE_SHA1}

  build-image-dbbackup:
    executor: noos-ci/default
    steps:
      - checkout
      - noos-ci/docker-build-image:
          registry-provider: docker
          image-context: ./docker/dbbackup
          image-name: dbbackup
          image-tag: ${CIRCLE_SHA1}

  build-image-jupyterlab:
    executor: noos-ci/default
    steps:
      - checkout
      - noos-ci/docker-build-image:
          registry-provider: docker
          image-context: ./docker/jupyterlab
          image-name: jupyterlab
          image-tag: ${CIRCLE_SHA1}


# -----------------
# Pipeline workflow
# -----------------

workflows:

  build-image-circleci:
    jobs:
      - hold:
          <<: *hold-master-only
      - build-image-circleci:
          <<: *deploy-master-only

  build-image-dbbackup:
    jobs:
      - hold:
          <<: *hold-master-only
      - build-image-dbbackup:
          <<: *deploy-master-only

  build-image-jupyterlab:
    jobs:
      - hold:
          <<: *hold-master-only
      - build-image-jupyterlab:
          <<: *deploy-master-only
