---
version: 2.1

default:
  filter: &filter-master-only
    branches:
      only: master
  hold: &hold-master-only
    type: approval
    filters:
      <<: *filter-master-only
  build: &build-master-only
    context: DOCKERHUB_SHARED
    filters:
      <<: *filter-master-only
  manual-build: &manual-build-master-only
    requires:
      - hold
    <<: *build-master-only

parameters:
  montly_trigger:
    type: boolean
    default: false


# ----------------
# Orbs declaration
# ----------------

orbs:

  noos-ci: noosenergy/noos-ci@0.1.15


# --------------
# Pipeline tasks
# --------------

jobs:

  build-image-circleci:
    executor: noos-ci/default
    steps:
      - checkout
      - noos-ci/docker-build-image:
          registry-provider: docker
          image-context: ./docker/circleci
          image-name: circleci
          image-tag: ${CIRCLE_SHA1}

  build-image-dbbackup:
    executor: noos-ci/default
    steps:
      - checkout
      - noos-ci/docker-build-image:
          registry-provider: docker
          image-context: ./docker/dbbackup
          image-name: dbbackup
          image-tag: ${CIRCLE_SHA1}

  build-image-jupyterlab:
    executor: noos-ci/default
    steps:
      - checkout
      - noos-ci/docker-build-image:
          registry-provider: docker
          image-context: ./docker/jupyterlab
          image-name: jupyterlab
          image-tag: ${CIRCLE_SHA1}

  build-image-pyscript:
    executor: noos-ci/default
    steps:
      - checkout
      - noos-ci/docker-build-image:
          registry-provider: docker
          image-context: ./docker/pyscript
          image-name: pyscript
          image-tag: ${CIRCLE_SHA1}


# -----------------
# Pipeline workflow
# -----------------

workflows:

  monthly-build-images:
    when: << pipeline.parameters.montly_trigger >>
    jobs:
      - build-image-circleci:
          <<: *build-master-only
      - build-image-dbbackup:
          <<: *build-master-only
      - build-image-jupyterlab:
          <<: *build-master-only
      - build-image-pyscript:
          <<: *build-master-only

  build-image-circleci:
    jobs:
      - hold:
          <<: *hold-master-only
      - build-image-circleci:
          <<: *manual-build-master-only

  build-image-dbbackup:
    jobs:
      - hold:
          <<: *hold-master-only
      - build-image-dbbackup:
          <<: *manual-build-master-only

  build-image-jupyterlab:
    jobs:
      - hold:
          <<: *hold-master-only
      - build-image-jupyterlab:
          <<: *manual-build-master-only

  build-image-pyscript:
    jobs:
      - hold:
          <<: *hold-master-only
      - build-image-pyscript:
          <<: *manual-build-master-only
