name: base
channels:
  - conda-forge
dependencies:
  - xeus-python
  - matplotlib
  - plotly
  - voila
  - dask-labextension
  - jupyter-server-proxy
  - ipywidgets
  # installing through pip to get latest stable version
  # - jupyterlab-git
  - bqplot
  - jupyter-flex
