name: base
channels:
  - conda-forge
dependencies:
  - nodejs>14 # Needed to have a newer version of nodejs for `jupyter lab build` 
  # metapackages
  - nomkl
  # enforcing numpy 1.*
  - numpy<2.0
  # z2jh setup
  - notebook
  - jupyterlab
  - jupyterhub
  # plotting
  - matplotlib
  - plotly
  - dash<3.0
  - ipywidgets
  - ipykernel
  # extensions
  - jupyterlab_pygments
  - jupyter-server-proxy
  - jupyterlab-git
  - jupyterlab_templates
  - jupyter-ai
  # updating cryptography
  - pyopenssl
  # extras
  - pip
  - pip:
    - jupyterlab-spreadsheet-editor
    - langchain-openai  # Needed for jupyter-ai OpenAI models
    - langchain-anthropic # Needed for jupyter-ai Anthropic models
