name: base
channels:
  - conda-forge
dependencies:
  # metapackages
  - nomkl
  # z2jh setup
  - notebook>=6.0.0
  - jupyterlab>=3.0.0
  - jupyterhub==3.0.0
  # debugging
  - xeus-python
  # plotting
  - matplotlib
  - plotly
  - dash>=2,<2.10
  - ipywidgets>=7.6
  - ipykernel>=6
  # extensions
  - jupyter-dash
  - jupyter-server-proxy
  - jupyterlab-git
  - jupyterlab-code-snippets
  - jupyterlab_templates<0.5 # jupyterlab>4 needed for 0.5+
  # updating cryptography
  - pyopenssl
  # extras
  - pip
  - pip:
    - jupyterlab-spreadsheet-editor<0.7 # jupyterlab>4 needed for 0.7+
