name: base
channels:
  - conda-forge
dependencies:
  - nodejs>14 # Needed to have a newer version of nodejs for `jupyter lab build` 
  # metapackages
  - nomkl
  # enforcing numpy 1.*
  - numpy<2.0
  # z2jh setup
  - notebook
  - jupyterlab<4 # Force downgrade to jupyterlab 3
  - jupyterhub
  # debugging
  - xeus-python
  # plotting
  - matplotlib
  - plotly
  - dash>=2,<2.10
  - ipywidgets
  - ipykernel
  # extensions
  - jupyter-dash
  - jupyterlab_pygments<0.3 # jupyterlab>4 needed for 0.3+ 
  - jupyter-server-proxy
  - jupyterlab-git
  - jupyterlab-code-snippets
  - jupyterlab_templates<0.5 # jupyterlab>4 needed for 0.5+
  # updating cryptography
  - pyopenssl
  # extras
  - pip
  - pip:
    - jupyterlab-spreadsheet-editor<0.7 # jupyterlab>4 needed for 0.7+
