name: base
channels:
  - conda-forge
dependencies:
  - xeus-python
  - matplotlib
  - plotly
  - voila
  - dask-labextension
  - jupyter-server-proxy
  - ipywidgets
  - bqplot
  # installing jupyterlab-git through pip to get latest stable version
  - pip:
    - jupyterlab-git==0.30.0b2
